plotly/plotly.rs

plotly/src/plot.rs
Add a `.to_inline_html()` method to `Plot` which can then be sent elsewhere for rendering.
For example, when using in Evcxr this turns this construction:
```rust
let plotly_file = "/tmp/plot.html";
plot.to_html(plotly_file);
let plotly_contents = fs::read_to_string(plotly_file).unwrap();
println!("EVCXR_BEGIN_CONTENT text/html\n{}\nEVCXR_END_CONTENT", plotly_contents);
fs::remove_file(plotly_file)?;
```
into this one-liner:
```rust
println!("EVCXR_BEGIN_CONTENT text/html\n{}\nEVCXR_END_CONTENT", plot.to_inline_html());
```
I debated adding a helper method for that wrapping - I'm happy to do so but I feel it would be presumptive without an OK from @igiagkiozis since they might not wish to officially support such usage, and interested parties probably are using …
=> Extract the render-to-string portion of to_html() into its own public method

CHANGELOG.md, plotly/src/layout.rs
add support for the tag "matches" in the Axis struct
=> add matches to Axis

plotly/examples/basic_charts.rs, plotly/src/lib.rs, plotly/src/scatter_polar.rs
Adds support for `scatterpolar` type plots.
Does not include the `transforms`, `uirevision`, `selected`, `unselected`, `thetaunit`, or any of the `*src` attributes.
I wasn't sure how to order the fields, so they use the order from `Scatter` and the new ones are inserted alphabetically, sort of.
=> add `ScatterPolar`

plotly/src/plot.rs
Plotly supported rendering the plot to HTML, and writing the output to a file, located at a user given path. Often however, it's desirable to split the process of rendering and the process of outputting the rendering. In addition, writing to a path is not always the most flexible, since you don't always have a file path. It can then be useful to be able to write the rendered entity to any writable buffer, which can be accomplished by using the std::io::Write trait instead of a path, which is what this change set does.
If desirable, I can also rework it to support the other output formats.
=>  Add a method to render the plot to anything implementing Write

.github/workflows/dev_ci.yml, .github/workflows/release_ci.yml, CHANGELOG.md, README.md, plotly/Cargo.toml, plotly/README.md, plotly/src/bindings.rs, plotly/src/lib.rs, plotly/src/plot.rs
This is a very simple PR which enables the project to be built in a wasm environment, tested on rust stable v1.60.0 with the command `cargo build --features wasm --target wasm-unknown-unknown`
Relates to issues #25 and #26.
This doesn't refactor any of the code, like a previous attempt, and just uses a new `wasm` feature and conditional compilation.
=> Support wasm

plotly/src/layout.rs
I've `Box`ed some of the largest fields in the `Layout` and `LayoutTemplate`structs because they were causing a stack overflow when running the tests in `debug` mode
=> Fix stack overflow in layout tests

plotly/examples/basic_charts.rs, plotly/examples/fundamentals.rs, plotly/examples/statistical_charts.rs, plotly/examples/subplots.rs, plotly/src/common/color.rs, plotly/src/common/mod.rs, plotly/src/layout/mod.rs, plotly/src/layout/themes.rs, plotly/src/lib.rs, plotly/src/private.rs, plotly/src/traces/box_plot.rs, plotly/src/traces/candlestick.rs, plotly/src/traces/contour.rs, plotly/src/traces/ohlc.rs, plotly/src/traces/sankey.rs, plotly/src/traces/scatter.rs, plotly/src/traces/scatter_polar.rs, plotly/src/traces/surface.rs
This is quite a large refactoring of the `color` module just to provide a slightly nicer implementation and interface. By prociding a public `Color` trait, end users can also implement it for their own color types, should they so desire. Tests are also included.
=> Refactor `color` module 

.gitignore, CHANGELOG.md, docs/book/src/getting_started.md, docs/book/src/plotly_rs.md, plotly/Cargo.toml, plotly/src/plot.rs, plotly/templates/inline_plot.html, plotly/templates/jupyter_notebook_plot.html, plotly/templates/static_plot.html, plotly_kaleido/src/lib.rs
This PR refactors the main API for showing and saving plots to more closely align with the familiar [plotly.py](https://plotly.com/python-api-reference/plotly.io.html#io).
`Plot::show()` displays the interactive HTML plot in the broswer.
`Plot::show_image(...)` displays a static image of the given format in the browser.
`Plot::to{_inline}_html(...)` renders the plot as an HTML string, either fully standalone or inline.
`Plot::write_html(...)` saves the image to an HTML file (kaleido not required).
`Plot::write_image(...)` uses kaleido to save a static image of the plot.
During the process, I've also refactored the HTML templates to use cleaner Javascript code, and added some tests, too.
=> Align API for saving/showing plots more closely with plotly.py

plotly/Cargo.toml, plotly/src/common/mod.rs, plotly/src/configuration.rs, plotly/src/layout/mod.rs, plotly/src/traces/bar.rs, plotly/src/traces/box_plot.rs, plotly/src/traces/candlestick.rs, plotly/src/traces/contour.rs, plotly/src/traces/heat_map.rs, plotly/src/traces/histogram.rs, plotly/src/traces/ohlc.rs, plotly/src/traces/sankey.rs, plotly/src/traces/scatter.rs, plotly/src/traces/scatter3d.rs, plotly/src/traces/scatter_polar.rs, plotly/src/traces/surface.rs
Significantly reduce noise within the code base by using this macro.
=> Add serde_with::skip_serializing_none macro

Cargo.toml, plotly/Cargo.toml, plotly/examples/buttons.rs, plotly/src/common/mod.rs, plotly/src/layout/mod.rs, plotly/src/layout/update_menu.rs, plotly/src/lib.rs, plotly/src/traces/bar.rs, plotly/src/traces/box_plot.rs, plotly/src/traces/candlestick.rs, plotly/src/traces/contour.rs, plotly/src/traces/heat_map.rs, plotly/src/traces/histogram.rs, plotly/src/traces/mod.rs, plotly/src/traces/ohlc.rs, plotly/src/traces/sankey.rs, plotly/src/traces/scatter.rs, plotly/src/traces/scatter3d.rs, plotly/src/traces/scatter_polar.rs, plotly/src/traces/surface.rs, plotly_derive/Cargo.toml, plotly_derive/src/lib.rs
_Thank you for this wonderful crate. I have personally found it much easier to make a plotly chart using this crate aided by the Rust type system as opposed to other options. Excited to contribute to this repository._
This PR introduces two changes:
There are a number of structs defined in this crate that have private fields and public functions to set the value for each of these fields. The `FieldSetter` procedural marco, when applied on a struct, auto-derives the public setter functions for each of the fields in the struct. The setter functions have a small number of distinct signatures based on the type of the field. Types such as `Dim, String, Color, NumOrString` get a special syntax. The procedural macro is defined in the `plotly_derive` crate. I have updated the `traces` and …
=> Button support and FieldSetter derive macro

CHANGELOG.md, plotly/src/plot.rs
=> Remove 'static lifetime requirement for `Plot.to_inline_html()`

CHANGELOG.md, plotly/src/plot.rs
Moved a few things around I got this to work on my Windows 10 machine seems like Spawn() does the trick!!
=> plot.show() fix

plotly/src/plot.rs
=> fix Plot.show()

CHANGELOG.md, plotly/src/plot.rs
Changes `show_with_default_app` for `target_os = "windows"` to make use of `spawn` in place of `output` when attempting to open the temporary HTML file using the user's default browser. Additionally provides arguments within a shared object delegating command formatting to `std::process:Command`, which going forwards I think will be a safe bet to ensure path correctness.
=> [#132]: Proposed Fix - "Plot `show` Method Not Working on Windows 10"

CHANGELOG.md, examples/3d_charts/src/main.rs, plotly/.gitignore, plotly/src/layout/mod.rs
Hi team,
I'd like to discuss a few things. There are a few remaining TODOs that need your attention. One specific concern involves handling arguments below zero to `AspectRatio` - I'd appreciate your advice on how to approach this.
Additionally, do you think it would be a good idea to rename the struct `LayoutScene` to just `Scene` or `Scene3D`?
I also updated the `customized_scatter3d_plot()` example in the `3d_charts` section. The example now includes most of the newly implemented fields and produces a very 'customized' plot.
I'm open to any feedback or suggestions you may have.
=> Add `LayoutScene`

plotly_kaleido/build.rs
With this change it is possible to use kaleido on Linux aarch64: https://repos.openhpc.community/stats/unique_visitors_per_month.svg
=> Automatically install kaleido binaries also on Linux aarch64

.github/workflows/ci.yml, examples/statistical_charts/src/main.rs, plotly/src/plot.rs, plotly_kaleido/src/lib.rs
- fix clippy suggestions 
- change workflow to use new 'main' branch 
- disable failing tests for windows, to be fixed in https://github.com/plotly/plotly.rs/issues/192
=> fix CI issues

plotly/Cargo.toml
Depend on `serde_with` version 2 or 3.
=> build(deps): Depend on serde_with version 2 or 3

CHANGELOG.md, CONTRIBUTING.md, README.md, docs/book/src/fundamentals.md, docs/book/src/fundamentals/jupyter_support.md, docs/book/src/fundamentals/ndarray_support.md, docs/book/src/getting_started.md, docs/book/src/plotly_rs.md, docs/book/src/recipes.md, docs/book/src/recipes/3dcharts.md, docs/book/src/recipes/basic_charts.md, docs/book/src/recipes/financial_charts.md, docs/book/src/recipes/scientific_charts.md, docs/book/src/recipes/statistical_charts.md, docs/book/src/recipes/subplots.md, plotly/Cargo.toml, plotly/src/plot.rs, plotly_derive/Cargo.toml, plotly_derive/README.md, plotly_kaleido/Cargo.toml, plotly_kaleido/README.md, plotly_kaleido/src/lib.rs
- change references from `master` to `main` branch
- change hyperlinks throught the repo to point to new repository url
- similarly, fix the hyperlinks in the Rust book
=> fix hyperlinks to point to new repository url

plotly/Cargo.toml, plotly/src/lib.rs, plotly/src/plot.rs
Recently, me and another `askama` maintainer forked the project into `rinja`. For more details about the why, I wrote a blog post [here](https://blog.guillaume-gomez.fr/articles/2024-07-31+docs.rs+switching+jinja+template+framework+from+tera+to+rinja). But in short: `rinja` is ahead of `askama` now in a lot of areas so I think going forward, your project will benefit more from it.
If you're not interested about this switch, don't hesitate to close the PR.
If you want more information about `rinja`, don't hesitate to ask!
=> Switch from askama to rinja

plotly/src/plot.rs
There are many Unix-like OSes that have xdg-open that are not Linux. Rather than enumerating DragonflyBSD, FreeBSD, NetBSD, OpenBSD, etc., change this "Linux" target to "Unix and not Android and not MacOS".
=> Generalize OS detection.

plotly/src/traces/bar.rs
Linked to #229 .
**This commit could prevent the existing code from compiling.**
I'm not sure if there are better fixes that make this field accept both integers and floats.
=> Make Bar.width to be Option<f64>

CHANGELOG.md, examples/basic_charts/src/main.rs, plotly/src/layout/mod.rs
This adds Axis category ordering along with the Axis category array.
This should fix #237
=> Add Categorical Axis Ordering and Axis Category Array

examples/3d_charts/src/main.rs, examples/scientific_charts/src/main.rs
In the examples of contour, surface, and heatmap plots, the names `x` and `y` in the code were swapped.
Using the examples as a starting point thus yielded flipped results.
This is only a naming issue, the functionality is left unchanged.
=> Examples: fix swapped x and y

CHANGELOG.md, docs/book/src/recipes/scientific_charts/contour_plots.md, examples/scientific_charts/src/main.rs, plotly/src/traces/contour.rs
Without this, the intervals between contour lines can only be integers.
I needed a smaller interval for a figure.
To Do:
=> Change Contours size to be `f64` instead of `usize`

examples/basic_charts/src/main.rs, plotly/src/common/mod.rs
Closes #145
Example using the api
=> Expose pattern fill api for histograms and bar charts

.github/workflows/book.yml, docs/book/src/fundamentals/ndarray_support.md, docs/book/src/getting_started.md, docs/book/src/plotly_rs.md, docs/book/src/recipes/3dcharts.md, examples/statistical_charts/src/main.rs
Fixes #248 
* Updated mdbook install command based on the recommended CI command (saves around 30seconds build time)
* Included git tag in the commit message to the gh-pages branch
* Fixed some broken links
* Fixed horizontal box plot example which was producing a vertical plot
=> Fix broken links and incorrect graphs in book

examples/3d_charts/src/main.rs, plotly/src/traces/mesh3d.rs
Fixes https://github.com/plotly/plotly.rs/issues/259.
I'm happy to make this a new function that only requires x, y, & z but it feels like that should be named `new` and another name should be used when providing i, j, & k.
=> Make i, j, k optional

README.md, examples/kaleido/Cargo.toml, examples/kaleido/src/main.rs, plotly/Cargo.toml, plotly/src/plot.rs, plotly_kaleido/Cargo.toml, plotly_kaleido/build.rs, plotly_kaleido/src/lib.rs
=> allow users to set Kaleido path via envionment variable

README.md
In the README.md, in the section _Usage Within a Wasm Environment_, I simply use `use_effect_with` instead of `use_effect_with_deps` which is deprecated in last Yew versions.
=> chore: use last version of use_effect_with in README.md

CHANGELOG.md, plotly/Cargo.toml, plotly/src/lib.rs, plotly/src/plot.rs
Rinja 0.2 was a fork of askama 0.12. Both projects were [merged again], and new versions of the project will be released under the name askama.
The feature `"with-axum"` is not needed anymore. The implementation for web-framework integrations was moved into its own crate. The `askama` crate does not have any problems with feature flag incompatibilities anymore.
[merged again]: <https://blog.guillaume-gomez.fr/articles/2025-03-19+Askama+and+Rinja+merge>
=> Update to askama 0.13.0

CHANGELOG.md, plotly/src/plot.rs
- disable show/render functionality when target_os is android
Closes #282
=> allow plotly to be compiled for android

plotly/src/plot.rs, plotly_kaleido/src/lib.rs
Hi 👋,
This PR fixes **#241** by **omitting `--disable-gpu` on macOS + arm64**.  
spec.json:
```json
{"format":"png","width":800,"height":600,"scale":1.0,"data":{"config":{},"data":[{"name":"Surface","type":"surface","x":[1.0,2.0,3.0],"y":[4.0,5.0,6.0],"z":[[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]]}],"layout":{}}}
```
```bash
cat spec.json | ./kaleido plotly \
--disable-gpu \
--allow-file-access-from-files \
--disable-breakpad \
--disable-dev-shm-usage \
--disable-software-rasterizer \
--single-process \
--no-sandbox \
> out.b64
```
```bash
cat out.b64
```
```json
{"code": 0, "message": "Success", "result": null, "version": "0.2.1"}
{"code":525,"message":"error creating static canvas/context for image server","pdfBgColor":null,"format":"png","result":null,"width":800,"height":600,"scale":1 …
```
=> #241 Add macOS-specific fixes and tests for Kaleido compatibility

CHANGELOG.md, plotly/src/plot.rs, plotly_kaleido/src/lib.rs
Static image generation doesn't work on my Framework laptop either which runs `Google Chrome 119.0.6045.199`. So it seems that `disable-gpu` flag is causing issues on more architectures/OSes.  
Decided to complete remove `disable-gpu` flag and with that, also to keep only the kaleido unittests added in PR #289 in favor of previous ones
=> remove disable-gpu flag for all targets

.github/workflows/ci.yml, CHANGELOG.md, examples/wasm-yew-callback-minimal/Cargo.toml, examples/wasm-yew-callback-minimal/README.md, examples/wasm-yew-callback-minimal/index.html, examples/wasm-yew-callback-minimal/src/main.rs, plotly/Cargo.toml, plotly/src/bindings.rs, plotly/src/callbacks.rs, plotly/src/lib.rs
- Added functionality of Click event callback
- Added wasm-yew-minimal-callback example in example docs
=> Added functionality for callbacks

docs/book/src/recipes/basic_charts/sankey_diagrams.md, examples/basic_charts/src/main.rs, plotly/src/traces/sankey.rs
=> fix sankey trace x/y node fields

docs/book/book.toml, docs/book/theme/header.hbs, plotly/src/plot.rs, plotly/templates/jupyter_notebook_plot.html, plotly/templates/plot.html, plotly/templates/static_plot.html
=> bump plotly.js version

docs/book/src/recipes/subplots/subplots.md, examples/subplots/src/main.rs
=> add example of subplots with multiple traces per subplot

plotly/src/plot.rs
This function is useful outside of the crate. Example use case: assembling multiple plotly chart `div` HTML elements into a single page, after injecting the plotly scripts via `offline_js_sources`. I've been able to then embed plotly graphs inside HTML pages generated with rusts `mdbook`, however I had to replicate this function externally - which is OK but creates a problem when bumping plotly as I would have to re-download these scripts which may change.
=> Make offline_js_sources pub

.github/workflows/release.yml, plotly_static/Cargo.toml
- plotly_static needs to be added to the same crates.io token
=> make plotly_static last crate to publish as currently will fail

CHANGELOG.md, README.md, docs/book/src/fundamentals/static_image_export.md, plotly/Cargo.toml, plotly/src/lib.rs, plotly_static/Cargo.toml, plotly_static/README.md, plotly_static/examples/README.md, plotly_static/src/lib.rs
- fix plotly_static example
- bump plotly_static and remove patch version from plotly_static when used in plotly crate
Closes #343
=> Re-export ImageFormat from plotly_static into plotly package

examples/maps/src/main.rs
=> fix maps examples

CHANGELOG.md, docs/book/src/recipes/basic_charts/scatter_plots.md, examples/basic_charts/src/main.rs, plotly/src/layout/mod.rs, plotly/src/layout/polar.rs
Happy for any feedback/advice while I work on this. Eventually closes #352.
=> feat(layout): add `LayoutPolar`
